# Generated by Django 2.0.5 on 2018-05-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('U', 'Used'), ('N', 'New'), ('LN', 'New, Open-Box')], max_length=20)),
            ],
            options={
                'ordering': ['update_date'],
            },
        ),
    ]
